Repository mozilla/fx-private-relay, pull requests merged in 2021-10, with the labels that each got.

#1222 Use new copy and order for filter
  privaterelay/templates/includes/dashboard-filter.html
Labels: need-review, hacktoberfest-accepted

#1125 Check user created before premium release
  .env-dist
  emails/models.py
  emails/tests/models_tests.py
  privaterelay/settings.py
Labels: hacktoberfest-accepted

#1184 Make the word filter wider
  static/scss/components/filter-bar.scss
Labels: hacktoberfest-accepted

#1191 Disallow whitespace-only labels
  privaterelay/templates/profile.html
  static/js/labels.js
Labels: hacktoberfest-accepted

#1276 use accept language to show country-specific price
  privaterelay/context_processors.py
  privaterelay/settings.py
  privaterelay/templates/newlanding/a/plans.html
  privaterelay/templatetags/relay_tags.py
Labels: need-review
