Repository mozilla/fx-private-relay, pull requests merged in 2021-08, with the labels that each got.

#1002 Update README with coding standards
  README.md
  docs/coding-standards.md
Labels: Needs Review

#1000 Fix #996 - Stop alias name from flickering
  static/scss/partials/dashboard.scss
Labels: :construction: WIP

#1014 Add premium/fxa data to body class
  privaterelay/templates/profile.html
Labels: :stop_sign: Do Not Merge

#1022 Stylelint updates
  .stylelintrc.json
  static/scss/components/banners.scss
  static/scss/components/buttons.scss
  static/scss/components/filter-bar.scss
  static/scss/includes/variables.scss
  static/scss/partials/banners.scss
  static/scss/partials/dashboard.scss
  static/scss/partials/footer.scss
  static/scss/partials/fx-bento.scss
  static/scss/partials/glocal-menu.scss
  static/scss/partials/header.scss
  static/scss/partials/main.scss
  static/scss/partials/onboarding.scss
  static/scss/partials/vpn-promo.scss
Labels: Needs Review

#1021 Fix #1015 - Survey background colors are now purple when user is premium
  static/scss/partials/banners.scss
Labels: Needs Review
