Repository mozilla/fx-private-relay, pull requests merged in 2022-06, with the labels that each got.

#2022 Fix tab order for the string filter toggle button
  frontend/src/components/dashboard/aliases/AliasList.tsx
Labels: size:XS

#2077 Clickable label for the "Block Promotional emails" track stop
  frontend/src/components/dashboard/aliases/BlockLevelSlider.module.scss
  frontend/src/components/dashboard/aliases/BlockLevelSlider.tsx
Labels: Review: XS

#2081 Update to Whitenoise 5.3.0
  requirements.txt
Labels: Review: XS

#2066 Clarify a workaround
  frontend/src/components/layout/navigation/AppPicker.module.scss
Labels: Review: µ

#2080 Use API-provided total counts
  frontend/src/pages/accounts/profile.page.tsx
  frontend/src/pages/accounts/profile.test.tsx
Labels: Review: µ

#2082 Show the user that subdomains will be lowercased
  frontend/__mocks__/modules/fluent__react.tsx
  frontend/src/components/dashboard/aliases/AliasList.tsx
  frontend/src/components/dashboard/subdomain/SearchForm.tsx
  frontend/src/pages/accounts/profile.test.tsx
Labels: Review: XS

#2088 Add a subdomain to be blocked from being used
  emails/blocklist.txt
  emails/tests/models_tests.py
Labels: Review: XS

#2102 Show breakage warning with tracker removal enabled
  frontend/src/pages/accounts/settings.page.tsx
Labels: Review: µ

#2100 Mask-specific counts of blocked trackers
  frontend/__mocks__/hooks/api/aliases.ts
  frontend/pendingTranslations.ftl
  frontend/src/apiMocks/handlers.ts
  frontend/src/apiMocks/mockData.ts
  frontend/src/components/dashboard/aliases/Alias.module.scss
  frontend/src/components/dashboard/aliases/Alias.tsx
  frontend/src/hooks/api/aliases.ts
Labels: Review: S

#2099 Indicator when tracker removal is enabled
  frontend/pendingTranslations.ftl
  frontend/src/components/dashboard/aliases/Alias.module.scss
  frontend/src/components/dashboard/aliases/Alias.tsx
Labels: Review: XS

#2107 Small styling refinements
  frontend/src/components/dashboard/aliases/Alias.module.scss
Labels: Review: µ

#2101 Profile-wide counts of blocked trackers
  frontend/__mocks__/hooks/api/profile.ts
  frontend/pendingTranslations.ftl
  frontend/src/apiMocks/mockData.ts
  frontend/src/hooks/api/profile.ts
  frontend/src/pages/accounts/profile.module.scss
  frontend/src/pages/accounts/profile.page.tsx
  frontend/src/pages/accounts/settings.page.tsx
Labels: Review: S

#2086 Validate custom addresses in the UI
  frontend/pendingTranslations.ftl
  frontend/src/components/dashboard/aliases/AddressPickerModal.test.tsx
  frontend/src/components/dashboard/aliases/AddressPickerModal.tsx
Labels: Review: XS

#2007 MPP-2011: Use only select allauth paths
  privaterelay/urls.py
Labels: Review: XS

#2116 MPP-2104 Put tracker removal UI behind a flag.
  frontend/src/pages/accounts/settings.page.tsx
Labels: Review: µ

#2113 MPP-1918 Update review count to 1055
  frontend/src/components/landing/Reviews.tsx
Labels: Review: µ

#2121 Validate custom masks on submission
  frontend/src/components/dashboard/aliases/AddressPickerModal.tsx
Labels: Review: µ
