Repository mozilla/fx-private-relay, pull requests merged in 2022-10, with the labels that each got.

#2595 MPP-2407 Relay phone masking upsell page strings don't match spec
  frontend/pendingTranslations.ftl
  frontend/src/components/phones/onboarding/PurchasePhonesPlan.module.scss
  frontend/src/components/phones/onboarding/PurchasePhonesPlan.tsx
Labels: Review: µ

#2603 MPP-2389: Fix mobile layout issue for phones onboarding page on Firefox for Android/iOS
  frontend/src/components/layout/navigation/Navigation.module.scss
  frontend/src/components/phones/onboarding/PurchasePhonesPlan.module.scss
Labels: hacktoberfest-accepted

#2599 MPP-1908 - FAQ for phone masking
  frontend/pendingTranslations.ftl
  frontend/src/pages/faq.page.tsx
Labels: Review: µ

#2598 Load all l10n files
  emails/templates/emails/wrapped_email.html
  frontend/src/functions/getL10n.ts
Labels: Review: XS

#2609 Ensure the phone FAQs are only shown if available
  frontend/src/pages/faq.page.tsx
  frontend/src/pages/faq.test.tsx
Labels: Review: µ

#2627 Fix postinstall script on Windows
  frontend/package-lock.json
  frontend/package.json
Labels: Review: µ

#2650 MPP-2439 - Disable buttons when no numbers found
  frontend/src/components/phones/onboarding/RelayNumberPicker.tsx
Labels: hacktoberfest-accepted, Review: µ

#2651 MPP-2435 - Disable register phone number mask button if no relay number is chosen
  frontend/src/components/phones/onboarding/RelayNumberPicker.tsx
Labels: hacktoberfest-accepted, Review: µ

#2649 Make the Forward/Block toggle look like a toggle
  frontend/pendingTranslations.ftl
  frontend/src/components/phones/dashboard/Dashboard.tsx
  frontend/src/components/phones/dashboard/PhoneDashboard.module.scss
Labels: Review: XS

#2648 Align "info" banners with design
  frontend/src/components/Banner.module.scss
  frontend/src/components/Banner.tsx
  frontend/src/pages/accounts/settings.page.tsx
Labels: Review: XS

#2666 Prevent line breaks in stats in Chinese
  frontend/src/components/dashboard/aliases/Alias.module.scss
Labels: Review: µ

#2673 Remove superfluous whitespace on mobile
  frontend/src/components/dashboard/aliases/Alias.module.scss
  frontend/src/components/dashboard/aliases/BlockLevelSlider.module.scss
Labels: Review: µ

#2552 Fix MPP-2381 - Add bundle price and savings callout (DNM)
  frontend/pendingTranslations.ftl
  frontend/src/components/landing/BundleBanner.tsx
  frontend/src/components/landing/PlanMatrix.tsx
  frontend/src/components/layout/navigation/whatsnew/WhatsNewMenu.tsx
  privaterelay/settings.py
Labels: :construction: WIP

#2672 Adjust thumb alignment for React Aria positioning
  frontend/src/components/dashboard/aliases/BlockLevelSlider.module.scss
Labels: Review: XS

#2696 Remove unneeded arrow on block level description
  frontend/src/components/dashboard/aliases/BlockLevelSlider.module.scss
Labels: Review: µ

#2699 Update plan ID for bundle
  privaterelay/settings.py
Labels: Review: µ

#2694 Tell virtual keyboards not to capitalise IDs
  frontend/src/components/dashboard/aliases/AddressPickerModal.tsx
  frontend/src/components/dashboard/subdomain/SearchForm.tsx
Labels: Review: µ
