Repository mozilla/fx-private-relay, pull requests merged in 2022-09, with the labels that each got.

#2436 MPP-2331 Static country code
  frontend/public/images/countryFlags/CA.svg
  frontend/public/images/countryFlags/US.svg
  frontend/src/components/phones/onboarding/RealPhoneSetup.module.scss
  frontend/src/components/phones/onboarding/RealPhoneSetup.tsx
Labels: Review: µ

#2410 MPP-2279 Add area code search for relay number suggestions.
  frontend/pendingTranslations.ftl
  frontend/src/components/Icons.tsx
  frontend/src/components/phones/onboarding/RelayNumberPicker.module.scss
  frontend/src/components/phones/onboarding/RelayNumberPicker.tsx
  frontend/src/hooks/api/relayNumber.ts
Labels: blocked

#2455 Allow modal close via outside click/pressing Esc
  frontend/src/components/phones/onboarding/RelayNumberConfirmationModal.tsx
  frontend/src/components/phones/onboarding/RelayNumberPicker.tsx
Labels: Review: µ

#2451 No negative numbers in the countdown timer
  frontend/src/components/layout/navigation/whatsnew/WhatsNewMenu.tsx
Labels: Review: µ

#2454 MPP-1898 - Relay number confirmation modal
  frontend/pendingTranslations.ftl
  frontend/src/components/phones/onboarding/PhoneOnboarding.tsx
  frontend/src/components/phones/onboarding/RelayNumberConfirmationModal.module.scss
  frontend/src/components/phones/onboarding/RelayNumberConfirmationModal.tsx
  frontend/src/components/phones/onboarding/RelayNumberPicker.tsx
Labels: Review: µ

#2468 MPP-2342 - Add flag check to prevent users for accessing phone page - redirected to premium page
  frontend/src/pages/phone.page.tsx
Labels: Review: µ

#2474 Use more widely supported flex- alignment values
  frontend/src/components/landing/carousel/ContentCards.module.scss
  frontend/src/pages/index.module.scss
  frontend/src/pages/premium.module.scss
Labels: Review: µ

#2467 Do not retry requests on server errors
  frontend/src/hooks/api/api.ts
Labels: Review: XS

#2477 Redirect user to /premium if they can't buy phones
  frontend/__mocks__/hooks/api/inboundContact.ts
  frontend/src/components/phones/onboarding/PhoneOnboarding.tsx
  frontend/src/components/phones/onboarding/PurchasePhonesPlan.tsx
  frontend/src/pages/phone.page.tsx
  frontend/src/pages/phone.test.tsx
Labels: Review: XS

#2480 MPP-2343
  frontend/package.json
  frontend/src/components/phones/dashboard/Dashboard.tsx
  frontend/src/components/phones/onboarding/RealPhoneSetup.tsx
  frontend/src/functions/formatPhone.test.ts
  frontend/src/functions/formatPhone.ts
Labels: Review: µ

#2476 Monthly/yearly toggle in phone onboarding
  frontend/pendingTranslations.ftl
  frontend/src/components/phones/onboarding/PurchasePhonesPlan.module.scss
  frontend/src/components/phones/onboarding/PurchasePhonesPlan.tsx
Labels: Review: XS

#2509 MPP-2200 Joint onboarding page
  frontend/pendingTranslations.ftl
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/layout/images/vpn-relay-logo.svg
  frontend/src/pages/images/mozilla-vpn-logo.svg
  frontend/src/pages/images/vpn-relay-panel-art.svg
  frontend/src/pages/vpn-relay-welcome.module.scss
  frontend/src/pages/vpn-relay-welcome.page.tsx
Labels: Review: XS

#2518 MPP-2348: Input field on the “Verify your true phone number” screen is moving with the screen when scrolling up and down
  frontend/src/components/phones/onboarding/RealPhoneSetup.module.scss
Labels: Review: µ

#2532 Replace underscores by hyphens in string IDs
  frontend/pendingTranslations.ftl
  frontend/src/components/landing/PlanMatrix.tsx
  frontend/src/pages/index.test.tsx
Labels: Review: µ

#2538 Pull in l10n updates daily
  .github/workflows/l10n-sync.yml
Labels: Review: µ

#2546 Authenticate the l10n repository sync
  .github/workflows/l10n-sync.yml
Labels: Review: µ

#2545 Use correct country code for Sweden
  privaterelay/settings.py
  privaterelay/tests/utils_tests.py
Labels: Review: µ

#2516 Add a banner promoting the Phones plan
  frontend/pendingTranslations.ftl
  frontend/src/components/landing/BundleBanner.module.scss
  frontend/src/components/landing/PhoneBanner.module.scss
  frontend/src/components/landing/PhoneBanner.tsx
  frontend/src/components/landing/images/bg-fingerprint.svg
  frontend/src/components/landing/images/phone-banner-woman.png
  frontend/src/components/landing/images/phone-banner-woman.webp
  frontend/src/components/landing/images/phone-float-account.svg
  frontend/src/components/landing/images/phone-float-clock.svg
  frontend/src/components/landing/images/phone-float-heart.png
  frontend/src/components/landing/images/phone-float-phone.png
  frontend/src/pages/index.page.tsx
  frontend/src/pages/premium.page.tsx
Labels: Review: XS

#2557 Use correct Plan IDs for Premium in Canada
  privaterelay/settings.py
Labels: Review: µ
