Repository mozilla/fx-private-relay, pull requests merged in 2022-11, with the labels that each got.

#2769 Pin the versions of our GitHub Actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/l10n-sync.yml
  .github/workflows/lint-pending-strings.yml
  .github/workflows/playwright.yml
Labels: Review: µ

#2779 Switch Twilio clients to initialize on first use
  phones/apps.py
  pyproject.toml
Labels: Review: XS

#2778 Update django-stubs to 1.13.0
  privaterelay/settings.py
  requirements.txt
Labels: Review: XS

#2775 MPP-2534: Add tests for `/fxa_rp_events/`, log `iat` claim age
  privaterelay/apps.py
  privaterelay/tests/views_tests.py
  privaterelay/views.py
Labels: Review: M

#2780 Add tips to the phone masking dashboard
  frontend/__mocks__/hooks/api/realPhone.ts
  frontend/src/components/phones/dashboard/Dashboard.tsx
  frontend/src/components/phones/dashboard/PhoneDashboard.module.scss
  frontend/src/pages/phone.module.scss
  frontend/src/pages/phone.page.tsx
Labels: Review: S

#2785 Add the Credential Manager integration announcement
  frontend/pendingTranslations.ftl
  frontend/src/apiMocks/mockData.ts
  frontend/src/components/layout/navigation/whatsnew/WhatsNewMenu.tsx
  frontend/src/components/layout/navigation/whatsnew/images/firefox-integration-hero.svg
  frontend/src/components/layout/navigation/whatsnew/images/firefox-integration-icon.svg
Labels: Review: XS

#2751 MPP-2498: Localize API error messages
  api/tests/views_tests.py
  api/views/__init__.py
  emails/models.py
Labels: :stop_sign: Do Not Merge, Review: XS

#2836 Revert "Bump react, react-dom and @types/react in /frontend"
  frontend/package-lock.json
  frontend/package.json
Labels: Review: µ

#2835 Explicitly enumerate known Waffle flags
  frontend/src/functions/waffle.ts
  frontend/src/hooks/api/runtimeData.ts
Labels: Review: µ

#2840 Add more anchor link targets
  frontend/src/components/dashboard/aliases/AliasList.tsx
  frontend/src/hooks/flaggedAnchorLinks.ts
  frontend/src/pages/index.page.tsx
  frontend/src/pages/premium.page.tsx
Labels: Review: µ

#2844 Update dismissal status when the key changes
  frontend/__mocks__/functions/cookies.ts
  frontend/src/hooks/localDismissal.test.ts
  frontend/src/hooks/localDismissal.ts
Labels: Review: XS

#2847 Align the "ghost" track stop with the slider
  frontend/src/components/dashboard/aliases/BlockLevelSlider.module.scss
Labels: Review: µ

#2848 Attach string filter match count to input
  frontend/src/components/dashboard/aliases/AliasList.module.scss
Labels: Review: µ

#2818 Remove Django support for site rendering
  emails/context_processors.py
  privaterelay/context_processors.py
  privaterelay/settings.py
  privaterelay/templates/faq.html
  privaterelay/templates/home.html
  privaterelay/templatetags/__init__.py
  privaterelay/templatetags/relay_tags.py
  static/images/newlanding/ribbon-plan.svg
Labels: Review: XS

#2819 Use decouple.CSV for comma-separated settings
  emails/models.py
  emails/tests/models_tests.py
  phones/tests/models_tests.py
  privaterelay/management/commands/update_phone_remaining_stats.py
  privaterelay/settings.py
Labels: Review: µ

#2805 MPP-2562: With flag `multi_replies`, choose relay text recipient by prefix
  api/tests/phones_views_tests.py
  api/views/phones.py
  emails/models.py
  phones/models.py
  privaterelay/ftl_bundles.py
  privaterelay/pending_locales/en/pending.ftl
  pyproject.toml
Labels: Review: L
