Repository mozilla/fx-private-relay, pull requests merged in 2022-07, with the labels that each got.

#2157 Fix class syntax for the phone nav link
  frontend/src/components/layout/navigation/Navigation.tsx
Labels: Review: µ

#2158 Add an animation to the custom mask tip
  frontend/public/animations/tips/custom-alias.mp4
  frontend/public/animations/tips/custom-alias.webm
  frontend/src/components/dashboard/tips/CustomAliasTip.module.scss
  frontend/src/components/dashboard/tips/CustomAliasTip.tsx
Labels: Review: µ

#2176 Consistently position block level descriptions
  frontend/src/components/dashboard/aliases/BlockLevelSlider.module.scss
  frontend/src/components/dashboard/aliases/images/umbrella-closed.svg
  frontend/src/components/dashboard/aliases/images/umbrella-semi.svg
Labels: Review: µ

#2230 Align UI with updated API
  frontend/__mocks__/hooks/api/profile.ts
  frontend/src/apiMocks/mockData.ts
  frontend/src/components/dashboard/aliases/Alias.tsx
  frontend/src/hooks/api/profile.ts
  frontend/src/pages/accounts/profile.page.tsx
Labels: Review: XS

#2231 Allow periods in custom mask addresses
  emails/models.py
  emails/tests/models_tests.py
  frontend/pendingTranslations.ftl
  frontend/src/components/dashboard/aliases/AddressPickerModal.test.tsx
  frontend/src/components/dashboard/aliases/AddressPickerModal.tsx
Labels: Review: XS

#2229 Fix link to Firefox for mobile
  frontend/src/components/layout/navigation/AppPicker.tsx
Labels: Review: µ

#2215 Use overlayTrigger instead of menuTrigger
  frontend/src/pages/accounts/profile.page.tsx
Labels: Review: XS

#2178 Mention submodule updates in docs
  docs/frontend-architecture.md
Labels: Review: µ

#2245 Use consistent size for tracker blocking icon
  frontend/src/components/dashboard/aliases/Alias.module.scss
Labels: Review: µ

#2265 Update Tracker Removal release date in News
  frontend/src/components/layout/navigation/whatsnew/WhatsNewMenu.tsx
Labels: Review: µ

#2268 MPP-2002 measure tracker removal feature usage
  emails/apps.py
  emails/signals.py
  emails/tests/models_tests.py
  emails/tracker_lists/level-one-tracker.json
  emails/tracker_lists/level-two-tracker.json
Labels: Effort: S
