Repository mozilla/fx-private-relay, pull requests merged in 2022-08, with the labels that each got.

#2266 Recruit new interview participants
  frontend/src/components/layout/topmessage/InterviewRecruitment.tsx
  frontend/src/components/layout/topmessage/TopMessage.tsx
Labels: Review: XS

#2256 Add API mocks for the /realphone/ API
  frontend/src/apiMocks/handlers.ts
  frontend/src/apiMocks/mockData.ts
  frontend/src/hooks/api/phone.ts
Labels: Review: XS

#2300 Increase timeout for axe tests to reduce flakiness
  frontend/src/pages/accounts/profile.test.tsx
  frontend/src/pages/accounts/settings.test.tsx
  frontend/src/pages/faq.test.tsx
  frontend/src/pages/index.test.tsx
  frontend/src/pages/phone.test.tsx
  frontend/src/pages/premium.test.tsx
  frontend/src/pages/premium/waitlist.test.tsx
Labels: Review: µ

#2302 First leg of Phone QA feedback incorporation
  frontend/src/components/layout/navigation/Navigation.tsx
  frontend/src/pages/phone.page.tsx
Labels: Review: XS

#2301 Add clearer tracker removal breakage warnings
  frontend/pendingTranslations.ftl
  frontend/src/components/dashboard/aliases/Alias.tsx
  frontend/src/components/layout/navigation/whatsnew/WhatsNewMenu.tsx
  frontend/src/pages/accounts/profile.page.tsx
  frontend/src/pages/accounts/settings.page.tsx
  frontend/src/pages/faq.page.tsx
  frontend/src/pages/tracker-report.page.tsx
Labels: Review: µ

#2348 MPP-2282 - Limit input field length to 6 characters
  frontend/src/components/phones/onboarding/RealPhoneSetup.tsx
Labels: Review: µ

#2347 MPP-2289: Error state broken for true phone number verification
  frontend/src/components/phones/onboarding/PhoneOnboarding.tsx
  frontend/src/components/phones/onboarding/RealPhoneSetup.module.scss
  frontend/src/components/phones/onboarding/RealPhoneSetup.tsx
Labels: Review: XS

#2357 MPP-2287 - Format rendered phone numbers in dashboard
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/phones/dashboard/Dashboard.tsx
  frontend/src/functions/formatPhone.ts
Labels: Review: µ

#2349 MPP-2276 Update logic for when real phone verification code has expired
  api/tests/phones_views_tests.py
  api/views/__init__.py
  api/views/phones.py
  frontend/pendingTranslations.ftl
  frontend/src/apiMocks/mockData.ts
  frontend/src/components/phones/onboarding/PhoneOnboarding.tsx
  frontend/src/components/phones/onboarding/RealPhoneSetup.module.scss
  frontend/src/components/phones/onboarding/RealPhoneSetup.tsx
  frontend/src/components/phones/onboarding/RelayNumberPicker.module.scss
  frontend/src/hooks/api/realPhone.ts
  frontend/src/hooks/api/runtimeData.ts
  phones/models.py
  phones/tests/models_tests.py
  privaterelay/settings.py
Labels: :bug: bug, Review: µ

#2359 MPP-2286 Prevent verified numbers from doing verification process again.
  api/tests/phones_views_tests.py
  api/views/phones.py
  phones/models.py
Labels: Review: µ

#2381 Outsource checking for === to computers
  frontend/.eslintrc.js
Labels: Review: µ

#2385 Improvements for phone masking
  frontend/public/images/countryFlags/CA.svg
  frontend/public/images/countryFlags/US.svg
  frontend/src/components/phones/onboarding/RealPhoneSetup.module.scss
  frontend/src/components/phones/onboarding/RealPhoneSetup.tsx
  frontend/src/components/phones/onboarding/RelayNumberPicker.tsx
  frontend/src/functions/formatPhone.test.ts
  frontend/src/functions/formatPhone.ts
  frontend/src/hooks/api/relayNumber.ts
Labels: Review: XS

#2394 List tracker blocking if Premium's unavailable
  frontend/src/components/landing/Plans.tsx
  frontend/src/pages/index.page.tsx
  frontend/src/pages/premium.page.tsx
Labels: Review: µ

#2384 Use a table for tabular log data
  frontend/src/components/phones/dashboard/PhoneDashboard.module.scss
  frontend/src/components/phones/dashboard/SendersPanelView.tsx
Labels: Review: XS

#2396 Make the dashboard switcher non-sticky
  frontend/pendingTranslations.ftl
  frontend/src/components/layout/Layout.module.scss
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/layout/navigation/DashboardSwitcher.module.scss
  frontend/src/components/layout/navigation/DashboardSwitcher.tsx
  frontend/src/components/layout/navigation/MobileNavigation.module.scss
  frontend/src/components/layout/navigation/MobileNavigation.tsx
  frontend/src/pages/accounts/profile.page.tsx
  frontend/src/pages/phone.page.tsx
Labels: Review: XS

#2395 MPP-2310 Remove ability to resubmit existing number for verification
  frontend/src/components/phones/onboarding/RealPhoneSetup.tsx
Labels: Review: XS

#2405 Allow up to 10 JS Dependabot PRs
  .github/dependabot.yml
Labels: Review: µ

#2425 Notify users of the intro pricing end in forwarded emails
  api/views/__init__.py
  emails/templates/emails/wrapped_email.html
  emails/templatetags/email_extras.py
  frontend/pendingTranslations.ftl
  frontend/public/static/images/email-images/clock-purple.png
  frontend/public/static/images/email-images/clock.svg
  frontend/src/apiMocks/mockData.ts
  frontend/src/components/CountdownTimer.tsx
  frontend/src/components/dashboard/ProfileBanners.tsx
  frontend/src/hooks/api/runtimeData.ts
  frontend/src/pages/index.page.tsx
  frontend/src/pages/premium.page.tsx
  privaterelay/settings.py
Labels: Review: XS

#2426 Add News entry for the intro pricing end
  frontend/__mocks__/hooks/api/runtimeData.ts
  frontend/pendingTranslations.ftl
  frontend/src/components/layout/navigation/whatsnew/WhatsNewContent.tsx
  frontend/src/components/layout/navigation/whatsnew/WhatsNewDashboard.test.tsx
  frontend/src/components/layout/navigation/whatsnew/WhatsNewMenu.module.scss
  frontend/src/components/layout/navigation/whatsnew/WhatsNewMenu.tsx
  frontend/src/components/layout/navigation/whatsnew/images/offer-countdown-icon.svg
  frontend/src/hooks/interval.ts
Labels: Review: XS

#2412 MPP-2325 + MPP-2326
  frontend/src/components/phones/onboarding/RealPhoneSetup.tsx
Labels: Review: µ
