Repository mozilla/fx-private-relay, pull requests merged in 2023-03, with the labels that each got.

#3175 Allow togglings flags other than manage_flags
  frontend/src/pages/flags.page.tsx
Labels: Review: µ

#3178 Set credential manager integration date: March 21
  frontend/src/components/layout/navigation/whatsnew/WhatsNewMenu.tsx
Labels: Review: µ

#3170 Mark two flaky tests as slow
  e2e-tests/specs/relay-e2e.spec.ts
  e2e-tests/specs/relay-general-functionality.spec.ts
Labels: Review: XS

#3216 MPP-2958 - Set general body text color and styling
  emails/templates/emails/wrapped_email.html
Labels: :bug: bug, Review: µ
