Repository mozilla/fx-private-relay, pull requests merged in 2023-06, with the labels that each got.

#3518 MPP-2084 - Update list of countries everywhere they are listed
  frontend/src/hooks/api/runtimeData.ts
  frontend/src/pages/faq.page.tsx
  frontend/src/pages/index.page.tsx
  frontend/src/pages/premium.page.tsx
Labels: Review: µ

#3571 MPP-3195: Remove rest of the `new_from_address` flag
  .env-dist
  frontend/src/apiMocks/mockData.ts
  frontend/src/hooks/api/runtimeData.ts
Labels: Review: µ

#3485 Fix layout issues with long email local-part or domain
  frontend/src/components/dashboard/aliases/AliasDeletionButton.module.scss
Labels: :bug: bug, good first issue, Review: µ

#3408 Add demo data to take screenshots from
  frontend/src/apiMocks/mockData.ts
  frontend/src/components/dashboard/ProfileBanners.tsx
Labels: Review: µ

#3605 MPP-3207 - Update address in email footers
  emails/templates/emails/first_time_user.html
  emails/templates/emails/first_time_user.txt
Labels: ✉️ email
