Repository mozilla/fx-private-relay, pull requests merged in 2023-11, with the labels that each got.

#4038 Add tests for upsell banner feature
  frontend/src/components/dashboard/ProfileBanners.tsx
  frontend/src/pages/accounts/profile.test.tsx
Labels: good first issue, hacktoberfest-accepted, technical debt

#4062 MPP-3545: Styling updates to email banners
  emails/templates/emails/reply_requires_premium.html
  emails/templates/emails/wrapped_email.html
  emails/tests/fixtures/domain_recipient_expected.email
  emails/tests/fixtures/emperor_norton_expected.email
  emails/tests/fixtures/inline_image_expected.email
  emails/tests/fixtures/message_id_in_brackets_expected.email
  emails/tests/fixtures/plain_text_expected.email
  emails/tests/fixtures/reply_requires_premium_first_expected.email
  emails/tests/fixtures/reply_requires_premium_second_expected.email
  emails/tests/fixtures/russian_spam_expected.email
  emails/tests/fixtures/single_recipient_expected.email
  emails/tests/fixtures/single_recipient_fr_expected.email
  emails/tests/fixtures/single_recipient_list_expected.email
Labels: Review: S

#4087 MPP-3562 CSAT banner not showing every 90 days on website
  frontend/src/components/layout/topmessage/CsatSurvey.tsx
Labels: Review: µ

#4109 Update to Node 18.18
  .circleci/config.yml
  frontend/netlify.toml
  frontend/package.json
  package.json
Labels: Review: µ

#4070 MPP-3478, MPP-3455, MPP-3479: Updates for custom mask creation
  frontend/pendingTranslations.ftl
  frontend/src/components/Icons.tsx
  frontend/src/components/dashboard/aliases/AliasGenerationButton.module.scss
  frontend/src/components/dashboard/aliases/AliasGenerationButton.tsx
  frontend/src/components/dashboard/aliases/AliasList.tsx
  frontend/src/components/dashboard/aliases/CustomAddressGenerationModal.module.scss
  frontend/src/components/dashboard/aliases/CustomAddressGenerationModal.tsx
  frontend/src/components/dashboard/aliases/MaskCard.tsx
  frontend/src/components/dashboard/subdomain/SubdomainInfoTooltip.tsx
  frontend/src/hooks/api/runtimeData.ts
  frontend/src/pages/accounts/profile.page.tsx
Labels: Review: S

#4143 MPP-3578 - Implement refined upsell banner logic
  frontend/public/images/woman-couch-left.svg
  frontend/src/components/dashboard/PremiumPromoBanners.tsx
  frontend/src/components/dashboard/ProfileBanners.tsx
  frontend/src/pages/accounts/profile.page.tsx
Labels: Review: XS

#4147 MPP-3578 - Make FF banner dismissible
  frontend/src/components/dashboard/ProfileBanners.tsx
Labels: Review: µ

#4148 MPP-3589 - Show news item only to free users
  frontend/src/components/layout/navigation/whatsnew/WhatsNewMenu.tsx
Labels: :stop_sign: Do Not Merge
