Repository mozilla/fx-private-relay, pull requests merged in 2023-01, with the labels that each got.

#2932 Mark localtunnel URLs as being local
  privaterelay/settings.py
Labels: Review: µ

#2971 Make one of the PlanMatrix CTAs the primary one
  frontend/src/components/landing/PlanMatrix.module.scss
  frontend/src/components/landing/PlanMatrix.tsx
Labels: Review: µ

#2972 Allow stats area to shrink if not all are visible
  frontend/src/components/dashboard/aliases/Alias.module.scss
Labels: Review: µ

#2976 Prevent waitlists from extending beyond the sides
  frontend/src/components/waitlist/WaitlistPage.module.scss
Labels: Review: µ

#2975 Preserve locally-stored mask-website associations
  frontend/src/hooks/localLabels.ts
  frontend/src/pages/accounts/settings.page.tsx
Labels: Review: µ

#2991 Update e2e tests for renamed navigation item
  e2e-tests/pages/dashboardPage.ts
Labels: Review: µ

#2678 MPP-2442 Avoid to break the button string in 2 lines
  frontend/pendingTranslations.ftl
  frontend/src/components/phones/onboarding/RelayNumberPicker.tsx
Labels: hacktoberfest-accepted, Review: µ

#2992 Show numpad when entering a verification code
  frontend/src/components/phones/onboarding/RealPhoneSetup.tsx
Labels: Review: µ

#3013 Consistently allow missing trailing slashes API routes
  api/tests/phones_views_tests.py
  api/tests/views_tests.py
  api/urls.py
Labels: Review: XS

#3042 MPP-2721: Handle uppercase letters in domain adresses
  emails/tests/views_tests.py
  emails/views.py
Labels: Review: S

#3043 Partially revert "Merge pull request #2940 from mozilla/MPP-2671-upda…
  emails/templates/emails/wrapped_email.html
  frontend/public/static/images/email-images/email-trackers-removed-icon.png
  frontend/public/static/images/email-images/relay-icon.png
  frontend/public/static/images/email-images/relay-logo-emails-dark-bg.png
  privaterelay/pending_locales/en/pending.ftl
Labels: Review: XS

#3059 Fix flaky test by mocking codetiming.Timer
  emails/management/commands/process_emails_from_sqs.py
  emails/tests/mgmt_process_emails_from_sqs_tests.py
Labels: Review: µ
