Repository mozilla/fx-private-relay, pull requests merged in 2024-01, with the labels that each got.

#4177 MPP-3390: CircleCI config refactor
  .circleci/config.yml
  .circleci/python_job.bash
Labels: Review: L

#4294 Enable new deletion modal in demo site
  frontend/src/apiMocks/mockData.ts
Labels: Review: µ

#4295 Avoid single tap being handled by both the deletion and confirmation button
  frontend/src/components/dashboard/aliases/AliasDeletionButtonPermanent.tsx
Labels: Review: XS
